pluginManagement { repositories { gradlePluginPortal(); maven { url = 'https://maven.minecraftforge.net/' } } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS); repositories { maven { url = 'https://maven.minecraftforge.net/' } } }
rootProject.name = 'blue-lock-mod'
