package com.bluelockmod.story;

public enum StoryState {
    PROLOGUE,
    CHARACTER_CREATION,
    ARRIVAL,
    FIRST_SELECTION_INTRO,
    FIRST_MATCH,
    FIRST_SELECTION_PROGRESS,
    FIRST_SELECTION_FINAL,
    SECOND_SELECTION_INTRO,
    SECOND_SELECTION_STAGE_1,
    SECOND_SELECTION_RIVAL_BATTLES,
    SECOND_SELECTION_ELITE,
    FINAL_STAGE,
    SEASON_1_COMPLETE
}
